version: '3.8'

services:

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - express.env
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: "dimon"
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: "di19772312mon"
    #   ME_CONFIG_MONGODB_URL: mongodb://dimon:di19772312mon@mongo:27017/
    depends_on:
      - mongo
    networks:
      - net-mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - mongo.env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "dimon"
    #   MONGO_INITDB_ROOT_PASSWORD: "di19772312mon"
    volumes:
      - ./mongodb_data:/data/db
      - ./mongodb_config:/data/configdb
    networks:
      - net-mongo
volumes:
  mongodb:
  mongodb_config:


networks:
  net-mongo:
    driver: bridge
